### PR TITLE
include request headers in details object for custom modify headers function

### PR DESCRIPTION
**Pull request by jakutis**

### CODE REVIEW

**Comment by sylingd** [comment]
Is it necessary to do this? How many cases do users require?
Every feature has other losses, such as performance, memory, etc. So I need to determine if a feature is necessary or not.

**Comment by jakutis** [comment]
@sylingd Currently users have ability to modify response only based on URL, which is weak and sometimes not useful (e.g. modifying 'Access-Control-Allow-Origin' response header to have value of 'Origin' request header). Because there is a quite easy way to give users custom functions request headers, then yes, it is necessary to do so.

Regarding performance:
* CPU impact is negligible - just store and retrieve a value from object by key;
* memory is also not a loss - after the custom function executed, the request headers reference is removed from the object and the memory is freed by the GC.

This is not a huge and complex feature, but a very useful and sometimes critical.

**Comment by sylingd** [comment]
I will merge this feature but it will be disable by default

**Comment by jakutis** [comment]
> I will merge this feature but it will be disable by default

Alright!

**Comment by sylingd** [comment]
Because Mozilla has blocked my account because of the my mail address repeatedly, 4.1.0 will not release the Firefox version.

**Pull request merged**
